// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gomap.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Graph struct {
	Node                 []*Node  `protobuf:"bytes,1,rep,name=node,proto3" json:"node,omitempty"`
	Edge                 []*Edge  `protobuf:"bytes,2,rep,name=edge,proto3" json:"edge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Graph) Reset()         { *m = Graph{} }
func (m *Graph) String() string { return proto.CompactTextString(m) }
func (*Graph) ProtoMessage()    {}
func (*Graph) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ba659ab2d55fb6, []int{0}
}

func (m *Graph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Graph.Unmarshal(m, b)
}
func (m *Graph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Graph.Marshal(b, m, deterministic)
}
func (m *Graph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Graph.Merge(m, src)
}
func (m *Graph) XXX_Size() int {
	return xxx_messageInfo_Graph.Size(m)
}
func (m *Graph) XXX_DiscardUnknown() {
	xxx_messageInfo_Graph.DiscardUnknown(m)
}

var xxx_messageInfo_Graph proto.InternalMessageInfo

func (m *Graph) GetNode() []*Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *Graph) GetEdge() []*Edge {
	if m != nil {
		return m.Edge
	}
	return nil
}

type Edge struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	From                 int64    `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   int64    `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Weight               float64  `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	ViaNodes             []int64  `protobuf:"varint,5,rep,packed,name=viaNodes,proto3" json:"viaNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Edge) Reset()         { *m = Edge{} }
func (m *Edge) String() string { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()    {}
func (*Edge) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ba659ab2d55fb6, []int{1}
}

func (m *Edge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Edge.Unmarshal(m, b)
}
func (m *Edge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Edge.Marshal(b, m, deterministic)
}
func (m *Edge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Edge.Merge(m, src)
}
func (m *Edge) XXX_Size() int {
	return xxx_messageInfo_Edge.Size(m)
}
func (m *Edge) XXX_DiscardUnknown() {
	xxx_messageInfo_Edge.DiscardUnknown(m)
}

var xxx_messageInfo_Edge proto.InternalMessageInfo

func (m *Edge) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Edge) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Edge) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *Edge) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Edge) GetViaNodes() []int64 {
	if m != nil {
		return m.ViaNodes
	}
	return nil
}

type Node struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Lat                  float64  `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	PlaceId              string   `protobuf:"bytes,4,opt,name=placeId,proto3" json:"placeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ba659ab2d55fb6, []int{2}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Node) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Node) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *Node) GetPlaceId() string {
	if m != nil {
		return m.PlaceId
	}
	return ""
}

func init() {
	proto.RegisterType((*Graph)(nil), "pb.Graph")
	proto.RegisterType((*Edge)(nil), "pb.Edge")
	proto.RegisterType((*Node)(nil), "pb.Node")
}

func init() { proto.RegisterFile("gomap.proto", fileDescriptor_98ba659ab2d55fb6) }

var fileDescriptor_98ba659ab2d55fb6 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3d, 0x4b, 0x04, 0x31,
	0x10, 0x86, 0xc9, 0xc7, 0x9d, 0x77, 0x73, 0x20, 0x32, 0x85, 0x04, 0xb1, 0x58, 0xb6, 0x4a, 0xb5,
	0x85, 0xfe, 0x04, 0x11, 0xb1, 0xb1, 0x98, 0xca, 0x36, 0x6b, 0xe2, 0xde, 0xc1, 0xdd, 0x4e, 0x58,
	0x83, 0xe2, 0xbf, 0x97, 0x19, 0xfc, 0x68, 0xec, 0xde, 0xf7, 0x79, 0x21, 0x4f, 0x18, 0xd8, 0x4d,
	0x7c, 0x4a, 0x75, 0xa8, 0x0b, 0x37, 0x46, 0x5b, 0xc7, 0xfe, 0x0e, 0x56, 0x0f, 0x4b, 0xaa, 0x7b,
	0xbc, 0x06, 0x3f, 0x73, 0x2e, 0xc1, 0x74, 0x2e, 0xee, 0x6e, 0x36, 0x43, 0x1d, 0x87, 0x27, 0xce,
	0x85, 0x94, 0xca, 0x5a, 0xf2, 0x54, 0x82, 0xfd, 0x5b, 0xef, 0xf3, 0x54, 0x48, 0x69, 0xbf, 0x80,
	0x97, 0x86, 0x08, 0xbe, 0x7d, 0x56, 0x79, 0xc3, 0xc4, 0x2d, 0x69, 0x16, 0xf6, 0xba, 0xf0, 0x29,
	0xd8, 0xce, 0x44, 0x47, 0x9a, 0xf1, 0x1c, 0x6c, 0xe3, 0xe0, 0x94, 0xd8, 0xc6, 0x78, 0x09, 0xeb,
	0x8f, 0x72, 0x98, 0xf6, 0x2d, 0xf8, 0xce, 0x44, 0x43, 0xdf, 0x0d, 0xaf, 0x60, 0xf3, 0x7e, 0x48,
	0xf2, 0x8d, 0xb7, 0xb0, 0xea, 0x5c, 0x74, 0xf4, 0xdb, 0xfb, 0x67, 0xf0, 0x12, 0xfe, 0x75, 0x5e,
	0x80, 0x3b, 0xa6, 0xa6, 0x4a, 0x43, 0x12, 0x95, 0xf0, 0xac, 0x4a, 0x21, 0x3c, 0x63, 0x80, 0xb3,
	0x7a, 0x4c, 0x2f, 0xe5, 0x31, 0xab, 0x74, 0x4b, 0x3f, 0x75, 0x5c, 0xeb, 0x75, 0x6e, 0xbf, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x10, 0x31, 0xc7, 0xbb, 0x2c, 0x01, 0x00, 0x00,
}
